services:
  bot:
    build: ./Bot
    environment:
      - MINIAPP_BOT_TOKEN=${MINIAPP_BOT_TOKEN}
      - SITE_HOST=${SITE_HOST}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    networks:
      - web
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    restart: always
  
  score_app:
    build: ./Score_app
    environment:
      - DATA_LIFE_TIME=${DATA_LIFE_TIME}
      - CLEAR_TIME=${CLEAR_TIME}
    networks:
      - web
    expose:
      - 8080
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    volumes:
      - ./games:/app/games
    restart: always

  server:
    build: ./Server
    expose:
      - 8080
    networks:
      - web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy
        restart: true
      mysql:
        condition: service_healthy
        restart: true
    volumes:
      - ./games:/app/games
      - ./static:/app/static
      - ./media:/app/media
    restart: always
    
  redis:
    image: redis
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 20s
      retries: 10
    restart: always
  
  mysql:
    image: mysql
    networks:
      - web
    environment:
      MYSQL_DATABASE: "Paperdb"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_USER: ${MYSQL_DB_USER}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
  
  nginx:
    build: ./nginx
    networks:
      - web
    ports:
      - 80:80
    depends_on:
      - redis
      - mysql
      - server
      - score_app
    volumes:
      - ./games:/app/games
      - ./static:/app/static
      - ./media:/app/media
    restart: always

networks:
  web:
    driver: bridge