services:
  bot:
    build: ./Bot
    environment:
      - MINIAPP_BOT_TOKEN=${MINIAPP_BOT_TOKEN}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    networks:
      - web
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    restart: always
  
  games_app:
    build: ./Games
    environment:
      - TMP_MAX_LIFE_TIME=${TMP_MAX_LIFE_TIME}
    networks:
      - web
    expose:
      - 8080
    depends_on:
      redis:
        condition: service_healthy
        restart: true
    volumes:
      - ./media:/app/media
    restart: always

  server:
    build: ./Paper
    expose:
      - 8080
    networks:
      - web
    environment:
      - MINIAPP_BOT_TOKEN=${MINIAPP_BOT_TOKEN}
      - SECRET_KEY=${SECRET_KEY}
      - DOMAIN=${DOMAIN}
      - SITE_HOST=${SITE_HOST}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_DB_USER=${MYSQL_DB_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      redis:
        condition: service_healthy
        restart: true
      mysql:
        condition: service_healthy
        restart: true
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./templates:/app/templates
    restart: always
    
  redis:
    image: redis
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    restart: always
  
  mysql:
    image: mysql
    networks:
      - web
    volumes:
      - ./dbdata:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_USER: ${MYSQL_DB_USER}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always
  
  certbot:
    build: ./certbot
    networks:
      - web
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./cert:/etc/letsencrypt
      - ./acme:/var/www/letsencrypt
    depends_on:
      - nginx
    restart: always

  nginx:
    build: ./nginx
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN: ${DOMAIN}
    depends_on:
      - redis
      - mysql
      - server
      - games_app
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./cert:/etc/letsencrypt
      - ./acme:/var/www/letsencrypt
    restart: always

networks:
  web:
    driver: bridge